# This is a basic workflow to help you get started with Actions

name: Find Temp dirs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: false

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v3

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "::group::Mount output"
          mount || echo failed to run mount
          echo "::endgroup::"
          echo HOME=$HOME
          env|grep -i tmp
          env|grep -i temp
          env|grep -i XDG
          echo "::group::/tmp contents"
          ls -la /tmp || echo could not access /tmp
          echo "::endgroup::"
          echo "::group::contents of RUNNER_TEMP"
          ls -la $RUNNER_TEMP || echo could not access RUNNER_TEMP
          echo "::endgroup::"
          echo "::group::contents of XDG_RUNTIME_DIR"
          ls -la $XDG_RUNTIME_DIR || echo could not access XDG_RUNTIME_DIR
          echo "::endgroup::"
        shell: bash
